
INSERT INTO TDD_CONVERT_CRUD_ENTITY (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('KM-METER','*1000');
INSERT INTO TDD_CONVERT_CRUD_ENTITY (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('METER-KM', '/1000');
INSERT INTO TDD_CONVERT_CRUD_ENTITY (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('INCH-METER','*0.025');
INSERT INTO TDD_CONVERT_CRUD_ENTITY (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('METER-INCH','/0.025');
INSERT INTO TDD_CONVERT_CRUD_ENTITY (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('FOOT-METER','*0.3048');
INSERT INTO TDD_CONVERT_CRUD_ENTITY (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('METER-FOOT','/0.3048');
INSERT INTO TDD_CONVERT_CRUD_ENTITY (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('MILE-METER','*1609.344');
INSERT INTO TDD_CONVERT_CRUD_ENTITY (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('METER-MILE','/1609.344');
INSERT INTO TDD_CONVERT_CRUD_ENTITY (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('MM-METER','/1000');
INSERT INTO TDD_CONVERT_CRUD_ENTITY (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('METER-MM','*1000');
INSERT INTO TDD_CONVERT_CRUD_ENTITY (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('CM-METER','/100');
INSERT INTO TDD_CONVERT_CRUD_ENTITY (FROM_UNIT_TO_UNIT, FORMULA) VALUES ('METER-CM','*100');


